import crypto from 'node:crypto'

/** Ids are generated by whoever creates the row — browser or server. */
export function newId(prefix) {
  return `${prefix}_${crypto.randomBytes(8).toString('hex')}`
}

export const newToken = () => crypto.randomBytes(32).toString('hex')
